[[libcleri]]
arch = "aarch64"
git-tree-sha1 = "e5ad7ad96b1e5b1de527659a61e109a9c9b29e58"
os = "macos"

    [[libcleri.download]]
    sha256 = "95563eb97b1ef38ec2ac260471ebba8dffa4891c50a81913b17b75b36c75a678"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.aarch64-apple-darwin.tar.gz"
[[libcleri]]
arch = "aarch64"
git-tree-sha1 = "67eff01c42d234ebc0dfb282e16f1086b3cd6c70"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "ea8b5be1c48267712cb05fa33ea0df84e11d246756472cca78004b395a50708c"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.aarch64-linux-gnu.tar.gz"
[[libcleri]]
arch = "aarch64"
git-tree-sha1 = "bedeaccf6b346738c23379c73af50ca362417859"
libc = "musl"
os = "linux"

    [[libcleri.download]]
    sha256 = "6ef12e0dc12e4eb7ff1062948a47bfa80aa36403765c71544f393458f31fba2a"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.aarch64-linux-musl.tar.gz"
[[libcleri]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8c625c78320bbc812b4ab26afc7c5b003a535124"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "cca0f1be5a4107e8311331e2bf172b6e38cf0a4b7983c2ce11cd18b90827be82"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.armv6l-linux-gnueabihf.tar.gz"
[[libcleri]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "faf984f358fa1ea316f1b821096e3ed6c33cc9de"
libc = "musl"
os = "linux"

    [[libcleri.download]]
    sha256 = "0d438bbacc32f5f4ce8e34d62d7e016f7575c9ed27bdeb1658a25c152c2af1a5"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.armv6l-linux-musleabihf.tar.gz"
[[libcleri]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e45db1eacc73a7998cd352074e775164841cd841"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "6c558856e999ccb0f4d9af3752e6bf59872d8f40f5e446f00adc06c954fc1b4c"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.armv7l-linux-gnueabihf.tar.gz"
[[libcleri]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e9b13c770873518f78e5b9b4acfe842f02f8b296"
libc = "musl"
os = "linux"

    [[libcleri.download]]
    sha256 = "6d6dc3fd63fa6d68ba71f53e77fc2764968ac3b57cb04c817090270fe14d38d8"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.armv7l-linux-musleabihf.tar.gz"
[[libcleri]]
arch = "i686"
git-tree-sha1 = "7a1e8d99773f0998a61eb98a3e11cd05b57a1fce"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "39141c1f3722b49ce8f975e0732b7aeaa286d635c988090a65a4f0b612d78292"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.i686-linux-gnu.tar.gz"
[[libcleri]]
arch = "i686"
git-tree-sha1 = "edc8898e61119855ac5f689f46c3f888136493a8"
libc = "musl"
os = "linux"

    [[libcleri.download]]
    sha256 = "a7dfe4e8fc4c11468dd1459250b37d9697b0b9c13aed09a70846b16fe5fa1efb"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.i686-linux-musl.tar.gz"
[[libcleri]]
arch = "i686"
git-tree-sha1 = "59a053615ea6ed3819109b53e983e53f6c2c8b82"
os = "windows"

    [[libcleri.download]]
    sha256 = "28688449d313e038f4dff16305e6956f901eaa9e638e912da179e8bd951a40d0"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.i686-w64-mingw32.tar.gz"
[[libcleri]]
arch = "powerpc64le"
git-tree-sha1 = "d227f5d9e69d5e57fc6604f6b80bdc4aafb82b6f"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "573bf0d20c1ba13b5b9d7c69042bcc70528475a8529fa4e263e41dd9a14801be"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.powerpc64le-linux-gnu.tar.gz"
[[libcleri]]
arch = "x86_64"
git-tree-sha1 = "04de163764a3d98c76b4ae43b4dfdbd7d728af89"
os = "macos"

    [[libcleri.download]]
    sha256 = "491941c341b8748d3b5c62641454b50c45b7aaa9e76b989ced41b231125cc5de"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.x86_64-apple-darwin.tar.gz"
[[libcleri]]
arch = "x86_64"
git-tree-sha1 = "72ff5141af7b192e7773ac6bfbe003b39fb9009c"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "e355dfa3413d5c374aea408b5f48e33003573812e12d4a547ef3697fbf8533dc"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.x86_64-linux-gnu.tar.gz"
[[libcleri]]
arch = "x86_64"
git-tree-sha1 = "3050eb9c25c3707101aae7beb0cc0c9bdfce8e91"
libc = "musl"
os = "linux"

    [[libcleri.download]]
    sha256 = "b81324d79c930ad06bdaf0a85f80e02b48afac0be1f6cb34bc9291c4d5a1b7a1"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.x86_64-linux-musl.tar.gz"
[[libcleri]]
arch = "x86_64"
git-tree-sha1 = "0e859443ba0eb98310224fa800eff04d9b840f43"
os = "freebsd"

    [[libcleri.download]]
    sha256 = "24f0f3bb9c41a4102111c0bc0e7aef2408919ce52f61b2b9bfafc229e2289688"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.x86_64-unknown-freebsd.tar.gz"
[[libcleri]]
arch = "x86_64"
git-tree-sha1 = "80597863da8ec3b9e3bda2a746f1c6e05bdfbd81"
os = "windows"

    [[libcleri.download]]
    sha256 = "3a377b364ab994bc3405a977cddc55f7f6e9b92e4f5c2f7e90c785d41ec338fc"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+3/libcleri.v0.12.1.x86_64-w64-mingw32.tar.gz"
