[[libcleri]]
arch = "aarch64"
git-tree-sha1 = "176555404589dc339367d1794cf182aa58617fd8"
os = "macos"

    [[libcleri.download]]
    sha256 = "654c0a57ecb9b7bd5b742f7a477633f8cf5eaa04d91837abe958453078c05b86"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.aarch64-apple-darwin.tar.gz"
[[libcleri]]
arch = "aarch64"
git-tree-sha1 = "b0c3092bc5edb39e068578536e8208be4a21d13e"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "731066358b4a13c5e0feefdc68f348ee6b62ccd7d8e842d2cba5e9517ecac124"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.aarch64-linux-gnu.tar.gz"
[[libcleri]]
arch = "aarch64"
git-tree-sha1 = "370c4694eac6c09ca023beba0777777d524eb0e0"
libc = "musl"
os = "linux"

    [[libcleri.download]]
    sha256 = "d3a8385fdcd85e8adb93d70543edeb02925a28fc3186792e3e5ac501223bf97d"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.aarch64-linux-musl.tar.gz"
[[libcleri]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5737793d8cde3ec52db94b9382177be63f3a0a03"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "9bec95201b4a168266023c033e0c1524bc4dcbeac07bfeaeaa19c899d61134ba"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.armv6l-linux-gnueabihf.tar.gz"
[[libcleri]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "edf40d3067964f37d6917c0196a8a22daaa57d26"
libc = "musl"
os = "linux"

    [[libcleri.download]]
    sha256 = "92bbded2e7d7ac1f8493dc1579aa715fc57593cf09cbe282497edffee9f30f28"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.armv6l-linux-musleabihf.tar.gz"
[[libcleri]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "541d7fcde2f4285f7ad1cd15c89aeee6c9b86fc6"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "68ba6a034bce560471311acf1afc5a766a5f93f30d151481a2e086ad7ee5390b"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.armv7l-linux-gnueabihf.tar.gz"
[[libcleri]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "662fd50ae5ab537de1950e07d31454d16c521f86"
libc = "musl"
os = "linux"

    [[libcleri.download]]
    sha256 = "73ee0851a904525ba89226026ed5e61d4e34d0d7c23c6d4015c850520c484bf4"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.armv7l-linux-musleabihf.tar.gz"
[[libcleri]]
arch = "i686"
git-tree-sha1 = "ec1b77695877bb1963471bc807e6550f4c550c84"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "49cffce00088674acf7c98d1a98f7fcaa95f1f7330ea613f23be6aa9ca4f670b"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.i686-linux-gnu.tar.gz"
[[libcleri]]
arch = "i686"
git-tree-sha1 = "170db9d833172e06b709d97c059bd37ba3485911"
libc = "musl"
os = "linux"

    [[libcleri.download]]
    sha256 = "821eec710d5e971cd945fd34df6b75c6f5f1db3e83e10cb5b6ce4b33ae3bd527"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.i686-linux-musl.tar.gz"
[[libcleri]]
arch = "i686"
git-tree-sha1 = "69d6480c5221c73cc80e401b8306e97d1b0189b4"
os = "windows"

    [[libcleri.download]]
    sha256 = "516026788d88deda18c7f3b7a6f3ce6d81cc8ebfbda26c8c424b0449ac680a86"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.i686-w64-mingw32.tar.gz"
[[libcleri]]
arch = "powerpc64le"
git-tree-sha1 = "c05953bb22c61c6d316b6e5ea22839a39789b876"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "c67098ef128857060c46538c3d9a41c408dd6cb4cd146bfd2d451ea118aaa90e"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.powerpc64le-linux-gnu.tar.gz"
[[libcleri]]
arch = "x86_64"
git-tree-sha1 = "675b083c4c5c7547b978df01a0238c65a0d09aef"
os = "macos"

    [[libcleri.download]]
    sha256 = "3ebe0efb551b991bfb750eb46b5fb6e2fc81f5397b5c0c7585535dae1b662882"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.x86_64-apple-darwin.tar.gz"
[[libcleri]]
arch = "x86_64"
git-tree-sha1 = "589211922ccf2d1cd090c9fa9c53ef3c9946d53e"
libc = "glibc"
os = "linux"

    [[libcleri.download]]
    sha256 = "d46d760ddf0166c10ab9717839c0b4a61c2469f9c7c2a21e1b221076e174d437"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.x86_64-linux-gnu.tar.gz"
[[libcleri]]
arch = "x86_64"
git-tree-sha1 = "3e5099a6fe0650013c943b71f6f060739aaeef30"
libc = "musl"
os = "linux"

    [[libcleri.download]]
    sha256 = "b4142dec0164da4688d5e5bdcb3e79baf94a0e7a870ed9bd9bb5e11ca382d2e4"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.x86_64-linux-musl.tar.gz"
[[libcleri]]
arch = "x86_64"
git-tree-sha1 = "52024b5346bee7887b341ba19d674afb487c6909"
os = "freebsd"

    [[libcleri.download]]
    sha256 = "dc2171ea07886c9a6a359402a951c231ba7fd5a52de2bf7cd66b389617313f4b"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.x86_64-unknown-freebsd.tar.gz"
[[libcleri]]
arch = "x86_64"
git-tree-sha1 = "94181076cab3edd2e04354156a93e2168ec8f624"
os = "windows"

    [[libcleri.download]]
    sha256 = "978204d912b38372f9062c3309129ecb490be90384b4776490743b3e11b58f9a"
    url = "https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/download/libcleri-v0.12.1+2/libcleri.v0.12.1.x86_64-w64-mingw32.tar.gz"
