# Autogenerated wrapper script for libcleri_jll for aarch64-apple-darwin
export libcleri

using PCRE2_jll
JLLWrappers.@generate_wrapper_header("libcleri")
JLLWrappers.@declare_library_product(libcleri, "libcleri.dylib.0")
function __init__()
    JLLWrappers.@generate_init_header(PCRE2_jll)
    JLLWrappers.@init_library_product(
        libcleri,
        "lib/libcleri.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
